m4/ax_llvm: update test to match new LLVM 5 discriminator support dependency
Commit 72b7f86b920 "Rebase autofdo toolchain", unconditionally added
enhanced discriminator support, which depends on LLVM library version 5
and above.

Commit f7ee8285dee "Make create_llvm_prof to use discriminator encoding"
adds to the unconditional LLVM 5 dependency by citing possible imprecision bugs
arising from mixing LLVM generated version objects with autofdo
create_llvm_prof built against a different LLVM library version.

Furthermore, github issue 55 shows that when building on a system with
installed LLVM libraries older than LLVM 5, we see the newly dependent code
fail to build, with:

g++ -DHAVE_CONFIG_H -I. -I./glog/src  -I. -I./glog/src  -I/usr/lib/llvm-4.0/include   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCREATE_LLVM_PROF -g -O2 -MT create_llvm_prof-sample_reader.o -MD -MP -MF .deps/create_llvm_prof-sample_reader.Tpo -c -o create_llvm_prof-sample_reader.o `test -f 'sample_reader.cc' || echo './'`sample_reader.cc
In file included from addr2line.h:24:0,
                 from addr2line.cc:17:
source_info.h: In member function ‘uint32 autofdo::SourceInfo::Offset(bool) const’:
source_info.h:63:37: error: ‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’
                 ? llvm::DILocation::getBaseDiscriminatorFromDiscriminator(
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source_info.h: In member function ‘uint32 autofdo::SourceInfo::DuplicationFactor() const’:
source_info.h:73:30: error: ‘getDuplicationFactorFromDiscriminator’ is not a member of ‘llvm::DILocation’
     return llvm::DILocation::getDuplicationFactorFromDiscriminator(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...

If we were building with llvm, we would be able to protect
that code by adding a preprocessor check for LLVM_VERSION_MAJOR >= 5,
but that's not always the case: create_llvm_prof is usually built with
gcc, only against the LLVM library headers:

$ find /usr/include/ -name DebugInfoMetadata.h | xargs grep -c getDuplicationFactorFromDiscriminator
/usr/include/llvm-4.0/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-3.8/llvm/IR/DebugInfoMetadata.h:0
/usr/include/llvm-5.0/llvm/IR/DebugInfoMetadata.h:2

Instead of adding a version check for the installed LLVM libraries, which
involves importing, say, an m4/ax_compare_version.m4 from another project,
just add detection for getBaseDiscriminatorFromDiscriminator and
getDuplicationFactorFromDiscriminator to the existing configure test source
when trying to determine whether to build create_llvm_prof with HAVE_LLVM set.
Otherwise, if HAVE_LLVM is not set, even though a create_llvm_prof binary is
built, it declines to run.

Also enhance user messaging, to call out that it's version 5 of the LLVM
library that's needed.

Signed-off-by: Kim Phillips <kim.phillips@arm.com>