Fix missing dependencies
Without this fix the create_llvm_prof was sometimes failing with errors like

autofdo_llvm1/third_party/perf_data_converter/src/quipper/compat/proto.h:14:10: fatal error: perf_data