Fix the build issue below which was not exposed when using llvm-10.
addr2line.cc:106:22: error: no matching constructor for initialization of 'devtools_crosstool_autofdo::SourceInfo'
    stack->push_back(SourceInfo(function_name, dir_name, file_name, start_line,