m4/ax_llvm: Fix undefined `llvm::DisableABIBreakingChecks' error in LLVM library test
On an Ubuntu system ./configure --llvm-config=`which llvm-config-5.0`,
generates this error:

configure:4596: checking whether g++ supports C++11 features by default
configure:4630: g++ -c -g -O2  conftest.cpp >&5
configure:4630: $? = 0
configure:4637: result: yes
configure:4834: checking whether we can compile and link with llvm(ProfileData)
configure:4869: g++ -o conftest -g -O2 -I/usr/lib/llvm-5.0/include   -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS   -Wl,-rpath /usr/lib/llvm-5.0/lib                       -L/usr/lib/llvm-5.0/lib                        -lLLVM-5.0 conftest.cpp  >&5
/tmp/cccqoy2O.o:(.data.rel+0x0): undefined reference to `llvm::DisableABIBreakingChecks'
collect2: error: ld returned 1 exit status
configure:4869: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "AutoFDO"
| #define PACKAGE_TARNAME "autofdo"
| #define PACKAGE_VERSION "0.18"
| #define PACKAGE_STRING "AutoFDO 0.18"
| #define PACKAGE_BUGREPORT "autofdo@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "autofdo"
| #define VERSION "0.18"
| /* end confdefs.h.  */
|
|
|                   #include "llvm/ProfileData/SampleProf.h"
|                   #include "llvm/IR/DebugInfoMetadata.h"
|
| int
| main ()
| {
|
|                   llvm::sampleprof::SampleRecord *R;
|                   R = new llvm::sampleprof::SampleRecord();
|                   llvm::DILocation::getBaseDiscriminatorFromDiscriminator(0);
|                   llvm::DILocation::getDuplicationFactorFromDiscriminator(0);
|                   return llvm::sampleprof::SPVersion();
|
|
|   ;
|   return 0;
| }
|
configure:4886: result: no
configure:4917: succeeded: no
configure:4920: WARNING: could not detect LLVM version 5 (or higher) libraries. Support for LLVM profiles disabled.

Fix by placing LLVM libraries after source file in compiler command line
for test program so that their symbols aren't removed before they're used.

Originally-by: Robert Walker <robert.walker@arm.com>
[removed generated files changes and enhanced commit text]
Signed-off-by: Kim Phillips <kim.phillips@arm.com>