autoconf: delete autogenerated files, add documentation on how to build ./configure
Re-do of commit e21776e "delete autogenerated files", in order to avoid build
bugs claimed against the raw git repo due to differences in distributions'
versions of how they run autoconf.  E.g., see github Issues #38 "aclocal-1.14:
command not found ", #55 "source_info.h:56:19: error:
‘getBaseDiscriminatorFromDiscriminator’ is not a member of ‘llvm::DILocation’
", #60, "Missing aclocal.m4", and so on.

Also adds the same instructions already in Makefile.ac on how to run autoconf,
but at the top of the INSTALL file, prior to the ./configure step, where it is
more visible to uninitiated users just looking to build from scratch.

Signed-off-by: Kim Phillips <kim.phillips@arm.com>